const NavRoutes = {
  Onboarding: 'Onboarding',
  TermsAndCondition: 'Terms And Condition',
  LanguageSelection: 'Language Selection',

  Welcome: 'Welcome',
  Drawer: 'Drawer',
  Home: 'Home',
  EMI: 'EMI',
  LoanEligibility: 'Loan Eligibility',
  CompareLoans: 'Compare Loans',
  TaxCalculation: 'Tax Calculation',
  SWP: 'SWP',
  SIP: 'SIP',
  EquityLinkedScheme: 'Equity Linked Scheme',
  Lumpsum: 'Lumpsum',
  FixedDeposit: 'Fixed Deposit',
  RecurringDeposit: 'Recurring Deposit',
  PublicProvidentFund: 'Public Provident Fund',
  SimpleAndCompound: 'Simple & Compound',
  CurrencyConversion: 'Currency Conversion',
  DiscountCalculator: 'Discount Calculator',
  PriceCalculator: 'Price Calculator',
  MarginCalculator: 'Margin Calculator',
  MarkupCalculator: 'Markup Calculator',
  OperatingMargin: 'Operating Margin',
  MarginWithSales: 'Margin With Sales',
  BankFinder: 'Bank Finder',
  ATMFinder: 'ATM Finder',
  AllCalculatorTheory: 'All Calculator Theory',
  FAQ: 'FAQ',
};

export default NavRoutes;
